### ISSUE TITLE
Observing End Effector Velocity for training the Robot 

### ISSUE THREAD

**Issue by murtazabasu** [AcutronicRobotics/gym-gazebo2#42]
Hi, i had been referring your environments for Reinforcement Learning. I just have a general question regarding the observation space which you have defined. It seems that you have 16 dimensions in your state space i.e. **`[Joint Angles, End_effector points (Difference between the target point and the current point of the end effector), Quaternion Error (Difference between target and the orientation of the end effector), and End Effector Velocities]`**   

**My question is it necessary to observe the end-effector velocities for training the robot and if so why?
Can it be excluded from the observation?**

**Comment by nzlz** [comment]
Hi @Murtaza786-oss ,
I am afraid this repo is not maintained anymore, so I will answer you and close the issue.

Due to the way we ended up training the network, which is executing actions instantaneously, it makes sense that you can discard end-effector velocities. Note that when we run an already trained network, we use [another driver](https://github.com/AcutronicRobotics/MARA/tree/dashing/mara_gazebo_plugins/src) (gazebo joint plugin) that manages velocity in an independent way.

The best way to make sure that you can discard it is to test it.
